// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keystone.proto

package keystone

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Sometimes grpc feels overkill for simple things.
type Key struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_f386c446c9c68353, []int{0}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Value struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_f386c446c9c68353, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_f386c446c9c68353, []int{2}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type KeyValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f386c446c9c68353, []int{3}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ServerInfo struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f386c446c9c68353, []int{4}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ClusterInfo struct {
	Peers                []string          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Dstore               map[string]string `protobuf:"bytes,2,rep,name=dstore,proto3" json:"dstore,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClusterInfo) Reset()         { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()    {}
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f386c446c9c68353, []int{5}
}

func (m *ClusterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterInfo.Unmarshal(m, b)
}
func (m *ClusterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterInfo.Marshal(b, m, deterministic)
}
func (m *ClusterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterInfo.Merge(m, src)
}
func (m *ClusterInfo) XXX_Size() int {
	return xxx_messageInfo_ClusterInfo.Size(m)
}
func (m *ClusterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterInfo proto.InternalMessageInfo

func (m *ClusterInfo) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *ClusterInfo) GetDstore() map[string]string {
	if m != nil {
		return m.Dstore
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "keystone.Key")
	proto.RegisterType((*Value)(nil), "keystone.Value")
	proto.RegisterType((*Nothing)(nil), "keystone.Nothing")
	proto.RegisterType((*KeyValue)(nil), "keystone.KeyValue")
	proto.RegisterType((*ServerInfo)(nil), "keystone.ServerInfo")
	proto.RegisterType((*ClusterInfo)(nil), "keystone.ClusterInfo")
	proto.RegisterMapType((map[string]string)(nil), "keystone.ClusterInfo.DstoreEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KeystoneClient is the client API for Keystone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeystoneClient interface {
	// Client interface: read/write key-value pairs
	Read(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	Write(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Nothing, error)
	// Server-server interface: cluster management
	ServerWrite(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Nothing, error)
	GetClusterInfo(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*ClusterInfo, error)
	Join(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Nothing, error)
}

type keystoneClient struct {
	cc *grpc.ClientConn
}

func NewKeystoneClient(cc *grpc.ClientConn) KeystoneClient {
	return &keystoneClient{cc}
}

func (c *keystoneClient) Read(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/keystone.Keystone/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoneClient) Write(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/keystone.Keystone/Write", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoneClient) ServerWrite(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/keystone.Keystone/ServerWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoneClient) GetClusterInfo(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := c.cc.Invoke(ctx, "/keystone.Keystone/GetClusterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keystoneClient) Join(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/keystone.Keystone/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeystoneServer is the server API for Keystone service.
type KeystoneServer interface {
	// Client interface: read/write key-value pairs
	Read(context.Context, *Key) (*Value, error)
	Write(context.Context, *KeyValue) (*Nothing, error)
	// Server-server interface: cluster management
	ServerWrite(context.Context, *KeyValue) (*Nothing, error)
	GetClusterInfo(context.Context, *Nothing) (*ClusterInfo, error)
	Join(context.Context, *ServerInfo) (*Nothing, error)
}

func RegisterKeystoneServer(s *grpc.Server, srv KeystoneServer) {
	s.RegisterService(&_Keystone_serviceDesc, srv)
}

func _Keystone_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoneServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keystone.Keystone/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoneServer).Read(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keystone_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoneServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keystone.Keystone/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoneServer).Write(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keystone_ServerWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoneServer).ServerWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keystone.Keystone/ServerWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoneServer).ServerWrite(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keystone_GetClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoneServer).GetClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keystone.Keystone/GetClusterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoneServer).GetClusterInfo(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Keystone_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeystoneServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/keystone.Keystone/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeystoneServer).Join(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Keystone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "keystone.Keystone",
	HandlerType: (*KeystoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Keystone_Read_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _Keystone_Write_Handler,
		},
		{
			MethodName: "ServerWrite",
			Handler:    _Keystone_ServerWrite_Handler,
		},
		{
			MethodName: "GetClusterInfo",
			Handler:    _Keystone_GetClusterInfo_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _Keystone_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keystone.proto",
}

func init() { proto.RegisterFile("keystone.proto", fileDescriptor_f386c446c9c68353) }

var fileDescriptor_f386c446c9c68353 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0x9a, 0xa6, 0x1f, 0x13, 0xac, 0x3a, 0x54, 0x2c, 0x01, 0x41, 0xf7, 0x20, 0x3d, 0x05,
	0x8d, 0x20, 0x56, 0xbc, 0xa9, 0x88, 0x06, 0x3c, 0x44, 0xd0, 0x73, 0x24, 0xa3, 0x86, 0x96, 0x6c,
	0xd9, 0x6c, 0x0b, 0xfb, 0x2b, 0x3c, 0xfb, 0x6f, 0x25, 0x9b, 0xc4, 0x8d, 0xb4, 0x07, 0xbd, 0xcd,
	0x9b, 0x79, 0x6f, 0x5e, 0xe6, 0x65, 0x61, 0x38, 0x23, 0x95, 0x4b, 0x9e, 0x91, 0xbf, 0x10, 0x5c,
	0x72, 0xec, 0xd7, 0x98, 0xed, 0x83, 0x1d, 0x92, 0xc2, 0x1d, 0xb0, 0x67, 0xa4, 0xc6, 0xd6, 0xa1,
	0x35, 0x19, 0x44, 0x45, 0xc9, 0x0e, 0xc0, 0x79, 0x8e, 0xe7, 0x4b, 0xc2, 0x11, 0x38, 0xab, 0xa2,
	0xa8, 0x86, 0x25, 0x60, 0x03, 0xe8, 0x3d, 0x72, 0xf9, 0x91, 0x66, 0xef, 0x2c, 0x80, 0x7e, 0x48,
	0xaa, 0x24, 0xaf, 0xed, 0x31, 0xf2, 0x76, 0x53, 0x7e, 0x0c, 0xf0, 0x44, 0x62, 0x45, 0xe2, 0x3e,
	0x7b, 0xe3, 0x38, 0x86, 0x5e, 0x9c, 0x24, 0x82, 0xf2, 0xbc, 0x52, 0xd6, 0x90, 0x7d, 0x59, 0xe0,
	0x5e, 0xcf, 0x97, 0xb9, 0xac, 0x98, 0x23, 0x70, 0x16, 0x44, 0xa2, 0xe0, 0xd9, 0xc5, 0x36, 0x0d,
	0x70, 0x0a, 0xdd, 0x24, 0x97, 0x5c, 0x14, 0x26, 0xf6, 0xc4, 0x0d, 0x8e, 0xfc, 0x9f, 0x7b, 0x1b,
	0x62, 0xff, 0x46, 0x73, 0x6e, 0x33, 0x29, 0x54, 0x54, 0x09, 0xbc, 0x29, 0xb8, 0x8d, 0xf6, 0x5f,
	0xbf, 0xff, 0xb2, 0x7d, 0x61, 0x05, 0x9f, 0x6d, 0x7d, 0xb8, 0xf6, 0xc1, 0x09, 0x74, 0x22, 0x8a,
	0x13, 0xdc, 0x32, 0xd6, 0x21, 0x29, 0x6f, 0xdb, 0x40, 0x1d, 0x10, 0x6b, 0xe1, 0x09, 0x38, 0x2f,
	0x22, 0x95, 0x84, 0xf8, 0x8b, 0xaa, 0xc7, 0xde, 0xae, 0xe9, 0xd5, 0xf1, 0xb6, 0xf0, 0x1c, 0xdc,
	0x32, 0xac, 0x7f, 0xea, 0xae, 0x60, 0x78, 0x47, 0xb2, 0x19, 0xdf, 0x3a, 0xcd, 0xdb, 0xdb, 0x98,
	0x15, 0x6b, 0xe1, 0x29, 0x74, 0x1e, 0x78, 0x9a, 0xe1, 0xc8, 0x10, 0xcc, 0x2f, 0xdb, 0x68, 0xf8,
	0xda, 0xd5, 0xaf, 0xeb, 0xec, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x1b, 0xaa, 0x7d, 0xba, 0x6f, 0x02,
	0x00, 0x00,
}
